sonar.organization=hiba05555
sonar.projectKey=hiba05555_stage_pfs_INTEGRATION_ia
sonar.sources=services,dataprotect-frontend/src,chatbot-service
sonar.exclusions=**/node_modules/**,database/**,**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info